name: Continuous Integration

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_call:
  
jobs:
  linting:
    name: Prettier, linting & type-checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install packages
        run: yarn install --prefer-offline --frozen-lockfile --non-interactive
      - name: ESLint check
        run: yarn eslint .
      - name: Prettier check
        run: yarn prettier . --check **/*.{js,ts,tsx}
      - name: Typescript check
        run: yarn check-types

  unit-tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install packages
        run: yarn install --prefer-offline --frozen-lockfile --non-interactive
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build